first_name=input('Input first name: ')
last_name=input('Input last name: ')
print('Hello, ' + first_name.capitalize() + ' ' + last_name.capitalize())
print('Hello, {} {}'.format(first_name, last_name))
print('Hello, {0} {1}'.format(first_name, last_name))
print('Hello, {1} {0}'.format(first_name, last_name))
print(f'Hello, {first_name} {last_name}')
